# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b5eafee2d29d9b52e183eba7911143694df3f836276445834b4c6aaa1980a437ea9dc948d8379838838af5d5e613dbb7a28fbdeca68aa4a28b9e5be38ec67bd

test:
  secret_key_base: bd9a2154fcb3e536c4bcaa40d025214b41042bac3529d8a5b21fb682e399d0c857eb475f265b814acc33c1331a99d9a04c45eb982a7ba5c4f542feac8ee9b07f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
